version: '3.8'

services:

  movies-db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./postgre/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    env_file:
      - .env.db
    expose:
      - 5432

  movies:
    image: mwtechdocker2/admin_panel:v1
    volumes:
      - static_volume:/usr/src/app/static
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - movies-db

  fastapi:
    build: ./fastapi
    volumes:
      - ./fastapi/:/usr/src/fastapi/
    expose:
      - "9000"
    env_file:
      - .env
    depends_on:
      - movies-db

  nginx:
    image: nginx:1.21.6
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
      - static_volume:/app/static
    depends_on:
      - movies
    ports:
      - "80:80"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms200m -Xmx200m
    expose:
      - 9200

  etl:
    image: mwtechdocker/etl:v1
    deploy:
      restart_policy:
        delay: 5s
        window: 5s
    env_file:
      - .env
    volumes:
      - ./etl/volumes/:/usr/src/etl/volumes/
    depends_on:
      - movies-db
      - elasticsearch

  redis:
    image: redis:alpine
    restart: always
    expose:
      - 6379

volumes:
  postgres_data:
  static_volume:

